services:
  - docker

before_install:
  - docker build -t parselynk/react-test -f ./client/Dockerfile.dev ./client

script:
  docker run -e CI=true parselynk/react-test npm test

after_success:
    - docker build -t rezakay/multi-client ./client
    - docker build -t rezakay/multi-worker ./worker
    - docker build -t rezakay/multi-server ./server
    - docker build -t rezakay/multi-nginx ./nginx

    #Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push rezakay/multi-client
    - docker push rezakay/multi-worker
    - docker push rezakay/multi-server
    - docker push rezakay/multi-nginx